services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: itasite
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  parser:
    build: .
    depends_on:
      - db
    restart: always
    command: node scheduler.js

  server:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_NAME=itasite
    restart: always
    command: node server.js

volumes:
  pgdata:
